name: 'mortgage_tracker'
version: '1.0.0'
config-version: 2

profile: 'mortgage_tracker'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  models:
  mortgage_tracker:
    staging:
      +materialized: table
      +schema: stg
    intermediate:
      +materialized: view
      +schema: int
    final:
      +materialized: table
      +schema: mart
